In [139]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [81]:
ch=pd.read_csv("E:\pythone/Churn.csv")

In [82]:
pd.set_option('display.max_columns',None) #

In [83]:
ch.head(2)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   

  PaperlessBilling     PaymentMethod  MonthlyCharges TotalCharges Churn  
0              Yes  Electronic check           29.85        29.85    No  
1               No      Mailed check           56.95       1889.5    No

In [91]:
ch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gender            7043 non-null   object 
 1   SeniorCitizen     7043 non-null   int64  
 2   Partner           7043 non-null   object 
 3   Dependents        7043 non-null   object 
 4   tenure            7043 non-null   int64  
 5   PhoneService      7043 non-null   object 
 6   MultipleLines     7043 non-null   object 
 7   InternetService   7043 non-null   object 
 8   OnlineSecurity    7043 non-null   object 
 9   OnlineBackup      7043 non-null   object 
 10  DeviceProtection  7043 non-null   object 
 11  TechSupport       7043 non-null   object 
 12  StreamingTV       7043 non-null   object 
 13  StreamingMovies   7043 non-null   object 
 14  Contract          7043 non-null   object 
 15  PaperlessBilling  7043 non-null   object 
 16  PaymentMethod     7043 non-null   object 


# Data Cleaning

In [85]:
ch.drop('customerID',axis=1,inplace=True)

In [86]:
ch['TotalCharges'] = ch['TotalCharges'].str.replace(',', '') 
ch['TotalCharges'] = pd.to_numeric(ch['TotalCharges'], errors='coerce') 

In [87]:
ch.isnull().sum()[ch.isnull().sum()>0]

TotalCharges    11
dtype: int64

In [88]:
ch.TotalCharges.fillna(ch.TotalCharges.mean(),inplace=True)

In [94]:
ch.select_dtypes(include='object').columns

Index([], dtype='object')

In [90]:
ch.StreamingMovies.unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [92]:
ch.gender.replace({'Female':0, 'Male':1},inplace=True)
ch.Partner.replace({'Yes':1, 'No':0},inplace=True)
ch.Dependents.replace({'Yes':1, 'No':0},inplace=True)
ch.PhoneService.replace({'Yes':1, 'No':0},inplace=True)
ch.MultipleLines.replace({'No phone service':0, 'No':0, 'Yes':1},inplace=True)
ch.InternetService.replace({'DSL':1, 'Fiber optic':2, 'No':0},inplace=True)
ch.OnlineSecurity.replace({'No internet service':0, 'No':0, 'Yes':1},inplace=True)
ch.OnlineBackup.replace({'No internet service':0, 'No':0, 'Yes':1},inplace=True)
ch.DeviceProtection.replace({'No internet service':0, 'No':0, 'Yes':1},inplace=True)
ch.TechSupport.replace({'No internet service':0, 'No':0, 'Yes':1},inplace=True)
ch.StreamingTV.replace({'No internet service':0, 'No':0, 'Yes':1},inplace=True)
ch.StreamingMovies.replace({'No internet service':0, 'No':0, 'Yes':1},inplace=True)
ch.Contract.replace({'Month-to-month':1, 'One year':2, 'Two year':3},inplace=True)
ch.PaperlessBilling.replace({'Yes':1, 'No':0},inplace=True)
ch.PaymentMethod.replace({'Electronic check':1, 'Mailed check':2, 'Bank transfer (automatic)':3,
       'Credit card (automatic)':4},inplace=True)
ch.Churn.replace({'Yes':1, 'No':0},inplace=True)

In [93]:
ch.head(2)

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0       0              0        1           0       1             0   
1       1              0        0           0      34             1   

   MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
0              0                1               0             1   
1              0                1               1             0   

   DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                 0            0            0                0         1   
1                 1            0            0                0         2   

   PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn  
0                 1              1           29.85         29.85      0  
1                 0              2           56.95       1889.50      0

In [95]:
ch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gender            7043 non-null   int64  
 1   SeniorCitizen     7043 non-null   int64  
 2   Partner           7043 non-null   int64  
 3   Dependents        7043 non-null   int64  
 4   tenure            7043 non-null   int64  
 5   PhoneService      7043 non-null   int64  
 6   MultipleLines     7043 non-null   int64  
 7   InternetService   7043 non-null   int64  
 8   OnlineSecurity    7043 non-null   int64  
 9   OnlineBackup      7043 non-null   int64  
 10  DeviceProtection  7043 non-null   int64  
 11  TechSupport       7043 non-null   int64  
 12  StreamingTV       7043 non-null   int64  
 13  StreamingMovies   7043 non-null   int64  
 14  Contract          7043 non-null   int64  
 15  PaperlessBilling  7043 non-null   int64  
 16  PaymentMethod     7043 non-null   int64  


# Sampling

In [96]:
from sklearn.model_selection import train_test_split
ch_train,ch_test=train_test_split(ch,test_size=.2)

In [97]:
ch_train.shape

(5634, 20)

In [98]:
ch_test.shape

(1409, 20)

In [49]:
# create x and y

In [99]:
ch_train_x = ch_train.drop(columns=['Churn'],axis=1)
ch_train_y = ch_train['Churn']
ch_test_x = ch_test.drop(columns=['Churn'],axis=1)
ch_test_y = ch_test['Churn']

In [100]:
ch_test_x.head()

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
7011       0              0        0           0       4             1   
4847       0              1        0           0      37             1   
4496       0              0        1           1      72             1   
6940       0              0        1           1      72             0   
6025       0              0        0           1      41             1   

      MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
7011              0                1               1             1   
4847              1                2               0             0   
4496              1                1               1             1   
6940              0                1               1             1   
6025              0                1               0             0   

      DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
7011                 0            1            0                0         1   
4847                 0            0            0                0         1   
4496                 1            1            1                1         3   
6940                 1            1            0                1         3   
6025                 0            0            0                0         1   

      PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  
7011                 1              2           60.40        272.15  
4847                 1              1           76.25       2841.55  
4496                 0              4           89.75       6595.90  
6940                 0              4           55.65       3880.05  
6025                 0              3           45.20       1841.90

In [101]:
ch_test_y.head()

7011    1
4847    1
4496    0
6940    0
6025    0
Name: Churn, dtype: int64

# Logistic Model

In [102]:
from sklearn.linear_model import LogisticRegression
logreg =LogisticRegression()

In [103]:
logreg.fit(ch_train_x,ch_train_y)

C:\Users\admin\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [104]:
logref_pred_train=logreg.predict(ch_train_x)
logref_pred_test=logreg.predict(ch_test_x)

In [107]:
from sklearn.metrics import confusion_matrix ,accuracy_score ,precision_score,recall_score

In [106]:
confusion_matrix(ch_test_y,logref_pred_test)

array([[925, 102],
       [186, 196]], dtype=int64)

In [108]:
accuracy_score(ch_test_y,logref_pred_test)

0.7955997161107168

In [112]:
precision_score(ch_test_y,logref_pred_test)

0.6577181208053692

In [113]:
recall_score(ch_test_y,logref_pred_test)

0.5130890052356021

# Decision Tree 

In [125]:
from sklearn.tree import DecisionTreeClassifier
dec=DecisionTreeClassifier(criterion='entropy')

In [126]:
dec.fit(ch_train_x,ch_train_y)

DecisionTreeClassifier(criterion='entropy')

In [127]:
dec_train_pred=dec.predict(ch_train_x)
dec_test_pred=dec.predict(ch_test_x)

In [128]:
confusion_matrix(ch_test_y,dec_test_pred)

array([[840, 187],
       [183, 199]], dtype=int64)

In [129]:
accuracy_score(ch_test_y,dec_test_pred)

0.7374024130589071

# Random Forest

In [120]:
from sklearn.ensemble import RandomForestClassifier
rfm=RandomForestClassifier()

In [121]:
rfm.fit(ch_train_x,ch_train_y)

RandomForestClassifier()

In [122]:
rfm_train_pred=rfm.predict(ch_train_x)
rfm_test_pred=rfm.predict(ch_test_x)

In [123]:
confusion_matrix(ch_test_y,rfm_test_pred)

array([[928,  99],
       [198, 184]], dtype=int64)

In [124]:
accuracy_score(ch_test_y,rfm_test_pred)

0.7892122072391767

# Ada Boosting on Logistic 

In [140]:
from sklearn.ensemble import AdaBoostClassifier
ada=AdaBoostClassifier(logreg)

In [141]:
ada_logreg=AdaBoostClassifier(logreg,n_estimators=100)
ada_logreg.fit(ch_train_x,ch_train_y)

AdaBoostClassifier(estimator=LogisticRegression(), n_estimators=100)

In [142]:
ada_logreg_pred_test=ada_logreg.predict(ch_test_x)

In [143]:
confusion_matrix(ch_test_y,ada_logreg_pred_test)

array([[917, 110],
       [181, 201]], dtype=int64)

In [144]:
accuracy_score(ch_test_y,ada_logreg_pred_test)

0.7934705464868701

In [152]:
ch=pd.read_csv("E:\pythone/Churn.csv")

pd.set_option('display.max_columns',None) #

ch.head(2)

ch.info()

ch.drop('customerID',axis=1,inplace=True)

ch['TotalCharges'] = ch['TotalCharges'].str.replace(',', '') 
ch['TotalCharges'] = pd.to_numeric(ch['TotalCharges'], errors='coerce') 

ch.isnull().sum()[ch.isnull().sum()>0]

ch.TotalCharges.fillna(ch.TotalCharges.mean(),inplace=True)

ch.select_dtypes(include='object').columns

ch.StreamingMovies.unique()

ch.gender.replace({'Female':0, 'Male':1},inplace=True)
ch.Partner.replace({'Yes':1, 'No':0},inplace=True)
ch.Dependents.replace({'Yes':1, 'No':0},inplace=True)
ch.PhoneService.replace({'Yes':1, 'No':0},inplace=True)
ch.MultipleLines.replace({'No phone service':0, 'No':0, 'Yes':1},inplace=True)
ch.InternetService.replace({'DSL':1, 'Fiber optic':2, 'No':0},inplace=True)
ch.OnlineSecurity.replace({'No internet service':0, 'No':0, 'Yes':1},inplace=True)
ch.OnlineBackup.replace({'No internet service':0, 'No':0, 'Yes':1},inplace=True)
ch.DeviceProtection.replace({'No internet service':0, 'No':0, 'Yes':1},inplace=True)
ch.TechSupport.replace({'No internet service':0, 'No':0, 'Yes':1},inplace=True)
ch.StreamingTV.replace({'No internet service':0, 'No':0, 'Yes':1},inplace=True)
ch.StreamingMovies.replace({'No internet service':0, 'No':0, 'Yes':1},inplace=True)
ch.Contract.replace({'Month-to-month':1, 'One year':2, 'Two year':3},inplace=True)
ch.PaperlessBilling.replace({'Yes':1, 'No':0},inplace=True)
ch.PaymentMethod.replace({'Electronic check':1, 'Mailed check':2, 'Bank transfer (automatic)':3,
       'Credit card (automatic)':4},inplace=True)
ch.Churn.replace({'Yes':1, 'No':0},inplace=True)

ch.head(2)

ch.info()

# sampling

from sklearn.model_selection import train_test_split
ch_train,ch_test=train_test_split(ch,test_size=.2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [153]:
df1=ch_train[ch_train.Churn==1]
ch_train=pd.concat([ch_train,df1])
ch_train.shape

(7164, 20)

In [154]:
ch_train.Churn.value_counts()

0    4104
1    3060
Name: Churn, dtype: int64

In [155]:
ch_train_x = ch_train.drop(columns=['Churn'],axis=1)
ch_train_y = ch_train['Churn']
ch_test_x = ch_test.drop(columns=['Churn'],axis=1)
ch_test_y = ch_test['Churn']

In [156]:
from sklearn.linear_model import LogisticRegression
logreg =LogisticRegression()

logreg.fit(ch_train_x,ch_train_y)

logref_pred_train=logreg.predict(ch_train_x)
logref_pred_test=logreg.predict(ch_test_x)

In [157]:
confusion_matrix(ch_test_y,logref_pred_test)

array([[849, 221],
       [ 79, 260]], dtype=int64)

In [161]:
accuracy_score(ch_test_y,logref_pred_test)

0.78708303761533

# Conclusion

The normal logistic model give max accuracy , precision score , recall_score